#ifndef DEFS_H
#define DEFS_H

#define GPS_BAUDRATE 9600
#define SD_CS_PIN 5

#define SCAN_DELAY 500
#define SCANNED_WIFI_LENGTH 256
#define RAW_BSSID_LENGTH 6
#define MAC_ADDR_LENGTH 18
#define RAW_MAC_LENGTH 10
#define MAX_NETWORKS 100

#endif